# Generated by Django 4.2.3 on 2023-08-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_membershipchange_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipchange",
            name="member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_change",
                to="core.memberchange",
            ),
        ),
    ]
