# Generated by Django 4.2.3 on 2023-08-31 09:15

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_membershipchange_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/",
                validators=[
                    core.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    ),
                ],
                verbose_name="photo",
            ),
        ),
        migrations.AddField(
            model_name="memberchange",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/",
                validators=[
                    core.validators.validate_image_size,
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    ),
                ],
                verbose_name="photo",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(
                choices=[
                    ("DH", "HONOR"),
                    ("D1", "FIRST_EXAM"),
                    ("D2", "SECOND_EXAM"),
                    ("D3", "THIRD_EXAM"),
                    ("D4", "FORTH_EXAM"),
                    ("R1", "R1"),
                    ("R2", "R2"),
                    ("R3", "R3"),
                ],
                default="DH",
                max_length=50,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="memberchange",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Declined", "DECLINED"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="membershipchange",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Approved", "APPROVED"),
                    ("Declined", "DECLINED"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
    ]
