# Generated by Django 4.2.3 on 2023-10-16 15:50

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_competition_alter_member_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="competitions.html",
            new_name="competitions",
        ),
        migrations.RenameField(
            model_name="memberchange",
            old_name="competitions.html",
            new_name="competitions",
        ),
        migrations.AlterField(
            model_name="competition",
            name="date",
            field=models.DateField(
                default=django.utils.datetime_safe.date.today, verbose_name="date"
            ),
        ),
    ]
