# Generated by Django 4.2.3 on 2023-10-16 17:14

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_competitions_html_member_competitions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos",
                        validators=[
                            core.validators.validate_image_size,
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            ),
                        ],
                        verbose_name="photo",
                    ),
                ),
                (
                    "competitions",
                    models.ManyToManyField(
                        blank=True, to="core.competition", verbose_name="competition"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(to="core.member", verbose_name="member"),
                ),
            ],
        ),
    ]
