# Generated by Django 4.2.3 on 2023-10-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_competitionregistration_remove_competition_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionregistration",
            name="competition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.competition",
            ),
        ),
        migrations.AlterField(
            model_name="competitionregistration",
            name="status",
            field=models.CharField(
                choices=[("Draft", "DRAFT"), ("Registered", "REGISTERED")],
                default="Draft",
                max_length=50,
                unique=True,
                verbose_name="status",
            ),
        ),
    ]
