# Generated by Django 4.2.3 on 2023-10-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_competitionregistration_competition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="competitions",
        ),
        migrations.AddField(
            model_name="competitionregistration",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.team"
            ),
        ),
    ]
