# Generated by Django 4.2.3 on 2023-10-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_team_competitions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[("Open", "OPEN"), ("Closed", "CLOSED")],
                default="Open",
                max_length=50,
                unique=True,
                verbose_name="status",
            ),
        ),
    ]
