# Generated by Django 4.2.3 on 2023-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_competition_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[("Open", "OPEN"), ("Closed", "CLOSED")],
                default="Open",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
