# Generated by Django 4.2.3 on 2023-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_competition_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(to="core.member", verbose_name="members"),
        ),
    ]
