# Generated by Django 4.2.3 on 2023-10-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionregistration",
            name="status",
            field=models.CharField(
                choices=[("Draft", "DRAFT"), ("Registered", "REGISTERED")],
                default="Draft",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
