# Generated by Django 4.2.3 on 2023-10-23 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_competitionregistration_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="competitions",
        ),
        migrations.RemoveField(
            model_name="memberchange",
            name="competitions",
        ),
    ]
