# Generated by Django 4.2.3 on 2023-10-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_member_competitions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.club"
            ),
        ),
    ]
