# Generated by Django 4.2.3 on 2023-11-06 22:16

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_competition_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="due_date",
            field=models.DateTimeField(
                default=django.utils.datetime_safe.date.today, verbose_name="due_date"
            ),
        ),
    ]
