# Generated by Django 4.2.3 on 2023-11-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_competition_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="min_members_number",
            field=models.IntegerField(default=6, verbose_name="min_members_number"),
        ),
    ]
