# Generated by Django 4.2.3 on 2023-11-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_team_min_members_number_reached"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="min_members_number_reached",
        ),
        migrations.AddField(
            model_name="team",
            name="min_members_number_not_reached",
            field=models.BooleanField(
                default=True, verbose_name="min_members_number_reached"
            ),
        ),
    ]
