# Generated by Django 4.2.3 on 2023-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_remove_team_min_members_number_reached_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "option",
                    models.CharField(
                        choices=[("Year", "YEAR")], max_length=50, verbose_name="option"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Greater", "GREATER"),
                            ("GreaterOrEqual", "GREATER_OR_EQUAL"),
                            ("LessThan", "LESS_THAN"),
                            ("LessThanOrEqual", "LESS_THAN_OR_EQUAL"),
                            ("Equal", "EQUAL"),
                            ("NotEqual", "NOT_EQUAL"),
                            ("AverageEqualTo", "AVERAGE_EQUAL_TO"),
                        ],
                        max_length=50,
                        verbose_name="condition",
                    ),
                ),
                ("value", models.FloatField(verbose_name="value")),
                (
                    "description",
                    models.TextField(
                        max_length=10000, null=True, verbose_name="description"
                    ),
                ),
                (
                    "exams",
                    models.ManyToManyField(
                        blank=True, to="core.exam", verbose_name="exams"
                    ),
                ),
            ],
        ),
    ]
