# Generated by Django 4.2.3 on 2023-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="min_members_number",
            field=models.IntegerField(default=6, verbose_name="min_members_number"),
        ),
    ]
