# Generated by Django 4.2.3 on 2023-11-20 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_rule_min_members_number_disciplines"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Disciplines",
            new_name="Discipline",
        ),
    ]
