# Generated by Django 4.2.3 on 2023-11-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_remove_rule_condition_remove_rule_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="disciplines",
            field=models.ManyToManyField(
                blank=True, to="core.discipline", verbose_name="disciplines"
            ),
        ),
    ]
