# Generated by Django 4.2.3 on 2023-12-08 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_competition_disciplines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discipline",
            name="rules",
        ),
        migrations.AddField(
            model_name="discipline",
            name="max_members_number",
            field=models.IntegerField(default=6, verbose_name="max_members_number"),
        ),
        migrations.AddField(
            model_name="rule",
            name="discipline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.discipline",
            ),
        ),
    ]
