# Generated by Django 4.2.3 on 2023-12-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_remove_team_min_members_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="disciplines",
        ),
        migrations.AddField(
            model_name="discipline",
            name="competition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.competition",
            ),
        ),
    ]
