# Generated by Django 4.2.3 on 2023-12-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_remove_competition_disciplines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionregistration",
            name="discipline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.discipline",
            ),
        ),
        migrations.AddField(
            model_name="competitionregistration",
            name="division",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.rule"
            ),
        ),
    ]
