# Generated by Django 4.2.3 on 2023-12-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_competitionregistration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionregistration",
            name="club",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.club"
            ),
        ),
    ]
